const recipes = [
    {
        'picture': 'croissant.jpg',
        'title': 'Leckere Croissants',
        'link': 'croissant',
        'preparationTime': '40 Min',
        'totalTime': '40 Min',
        'difficulty': 'normal',
        'date': '28.08.2006',
        'description': 'Am Vorabend fertige man aus den oben angegebenen Zutaten einen Hefeteig: Milch lauwarm werden lassen, Hefe mit etwas Zucker und Milch verrühren, kurz stehen lassen, dann mit allen Zutaten außer der Butter vermengen. Teig zugedeckt im Kühlschrank über Nacht stehen lassen. Den Teig aus dem Kühlschrank nehmen und auf einer Arbeitsfläche quadratisch ausrollen. Die Butter zwischen zwei Frischhaltefolien auf die halbe Größe des Quadrates formen, dann mit Mehl bestäuben und auf den Hefeteig legen. Das Mehl ist wichtig, da sich die Butter nicht mit dem Teig vermengen darf, da sonst kein Blätterteig entstehen kann. Also lieber etwas zu viel als zu wenig Mehl zwischen Butter und Hefeteig! Den Teig über die Butter briefumschlagartig legen, so dass von jeder Seite ein Dreieck über der Butter liegt und sie zudeckt. Dieses wird jetzt zu einem Rechteck ausgerollt, dieses Rechteck dreifach übereinander geschlagen und wieder ausgerollt. Das sollte man noch so 2 bis 3 Mal wiederholen. Dann werden Dreiecke geschnitten (etwa 12), und diese werden von der breiten Seite zu Hörnchen geformt. Den Backofen auf 220 bis 250°C vorheizen, hier scheiden sich die Geschmäcker: bis 220°C werden die Croissants (etwa 6 pro Blech) ca. 20 Minuten gebacken, bei 250°C etwa 12 Minuten. Das ist ein herrliches Frühstück!',
        'createdBy': 'Marco Loch',
        'profilePicture': 'profile',
        'subtitle': 'Bon Appétit',
        'ingredients': [
            {
                'ingredient': 'Butter',
                'amount': '250',
                'unit': 'g',
            },
            {
                'ingredient': 'Zucker',
                'amount': '50',
                'unit': 'g',
            },
            {
                'ingredient': 'Mehl',
                'amount': '500',
                'unit': 'g',
            },
            {
                'ingredient': 'Salz',
                'amount': '1',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Hefe',
                'amount': '42',
                'unit': 'g',
            },
            {
                'ingredient': 'Ei(er)',
                'amount': '2',
                'unit': '',
            },
            {
                'ingredient': 'Milch',
                'amount': '0.2',
                'unit': 'Liter',
            },
        ],
    },
    {
        'picture': 'salad.jpg',
        'title': 'Veganer Nudelsalat',
        'link': 'salat',
        'preparationTime': '15 Min',
        'totalTime': '15 Min',
        'difficulty': 'simpel',
        'date': '15.04.2015',
        'description': 'Erhitzen Sie zuerst etwa 3 Liter Wasser und geben Sie etwa 2 Teelöffel Salz ins Wasser. Geben Sie, wenn das Wasser kocht die Nudeln ins Wasser und lassen Sie sie kochen. Während die Nudeln kochen, erhitzen Sie einen Topf mit etwas Öl. Schneiden Sie eine kleine Zwiebel in kleine Würfel und braten Sie diese kurz an. Geben Sie nun die Erbsen und den Mais hinzu erhitzen diese. Geben Sie dort noch etwa einen TL Salz hinzu. Wenn die Nudeln gar sind, schütten Sie diese ab und stellen Sie etwa zeitgleich den Topf mit den Erbsen etc. vom Herd. Lassen Sie beides abkühlen. Schneiden Sie nun die Tomaten in kleine mundgerechte Stücke, ebenso die Gewürzgurken. Schneiden Sie jetzt auch die restliche Zwiebel in kleine Würfel. Vermischen Sie für die Soße Senf, Öl, Ketchup, Essig und ggf. die Sojasahne in einer großen Schüssel bis es eine cremige Masse wird. Geben Sie in die Soße noch etwas Salz (etwa einen TL) und Pfeffer. Geben Sie auch ein paar Kräuter wie z. B. Dill, Petersilie und Basilikum und die Soße. Jetzt müssen Sie nur noch alle Zutaten in eine Schüssel geben und alles gut verrühren.',
        'createdBy': 'Marco Loch',
        'profilePicture': 'profile',
        'subtitle': 'I Am Vegan & Like It',
        'ingredients': [
            {
                'ingredient': 'Penne oder andere Nudeln',
                'amount': '125',
                'unit': 'g',
            },
            {
                'ingredient': 'Mais',
                'amount': '0.25',
                'unit': 'Dose',
            },
            {
                'ingredient': 'Erbsen',
                'amount': '100',
                'unit': 'g',
            },
            {
                'ingredient': 'Zwiebel(n)',
                'amount': '0.5',
                'unit': 'kleine',
            },
            {
                'ingredient': 'Gewürzgurke(n)',
                'amount': '0.125',
                'unit': 'Glas',
            },
            {
                'ingredient': 'Tomate(n)',
                'amount': '1',
                'unit': '',
            },
            {
                'ingredient': 'Öl',
                'amount': '1',
                'unit': 'EL',
            },
            {
                'ingredient': 'Essig',
                'amount': '0.25',
                'unit': 'EL',
            },
            {
                'ingredient': 'Senf',
                'amount': '0.25',
                'unit': 'EL',
            },
            {
                'ingredient': 'Ketchup',
                'amount': '0.25',
                'unit': 'EL',
            },
            {
                'ingredient': 'Sojasahne',
                'amount': '0.5',
                'unit': 'TL',
            },
            {
                'ingredient': 'Basilikum',
                'amount': '1',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Dill',
                'amount': '1',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Petersilie',
                'amount': '1',
                'unit': 'Prise(n)',
            },
        ],
    },
    {
        'picture': 'tomatemozarella.jpg',
        'title': 'Tomate Mozarella',
        'link': 'tomatemozarella',
        'preparationTime': '10 Minuten',
        'totalTime': '10 Minuten',
        'difficulty': 'simpel',
        'date': '19.08.2022',
        'description': 'Das Gemüse in mundgerechte Stücke schneiden. Den Salat mit Öl und Balsamico vermengen. Nach Belieben mit Salz und Pfeffer würzen. Basilikum als Topping verwenden. Das ideale Gericht für den Sommer. ',
        'createdBy': 'Marco Loch',
        'profilePicture': 'profile',
        'subtitle': 'Ideal für den Sommer!',
        'ingredients': [
            {
                'ingredient': 'Tomate(n)',
                'amount': '4',
                'unit': 'kleine',
            },
            {
                'ingredient': 'Mozarella',
                'amount': '100',
                'unit': 'g',
            },
                       {
                'ingredient': 'Basilikum',
                'amount': '2',
                'unit': 'Blätter',
            },
            {
                'ingredient': 'Balsamico',
                'amount': '2',
                'unit': 'EL',
            },
            {
                'ingredient': 'Salz',
                'amount': '1',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Pfeffer',
                'amount': '1',
                'unit': 'Prise(n)',
            },
        ],
    },
    {
        'picture': 'kürbissuppe.jpg',
        'title': 'Kürbissuppe',
        'link': 'kürbissuppe',
        'preparationTime': '15 Minuten',
        'totalTime': '40 Minuten',
        'difficulty': 'simpel',
        'date': '31.08.2022',
        'description': 'Den Kürbis und die Kartoffeln in kleine Stücke schneiden. Die Zwiebeln und den Knoblauch kurz in Butter anbraten.  Wasser, Kartoffeln und Kürbis hinzugeben. Alles 10 - 15  Minuten kochen lassen, bis der Kürbis weich ist. Alles mit Salz und Pfeffer abschmecken. Nochmal 10 Minuten köcheln lassen und zum Schluss nochmals aufkochen lassen. Mit der Petersilie als Topping servieren. ',
        'createdBy': 'Michel Knüpfer',
        'profilePicture': 'profile',
        'subtitle': 'Cremige Kürbissuppe',
        'ingredients': [
            {
                'ingredient': 'Kürbis',
                'amount': '600',
                'unit': 'g',
            },
            {
                'ingredient': 'Kartoffel',
                'amount': '200',
                'unit': 'g',
            },
            {
                'ingredient': 'Butter',
                'amount': '10',
                'unit': 'g',
            },
            {
                'ingredient': 'Zwiebel',
                'amount': '40',
                'unit': 'g',
            },
            {
                'ingredient': 'Knoblauch',
                'amount': '1',
                'unit': 'Zehe(n)',
            },
            {
                'ingredient': 'Wasser',
                'amount': '200',
                'unit': 'ml',
            },
            {
                'ingredient': 'Salz',
                'amount': '1',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Pfeffer',
                'amount': '1',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Petersilie',
                'amount': '1',
                'unit': 'Prise(n)',
            },
        ],
    },
    {
        'picture': 'tomatensuppe.jpg',
        'title': 'Tomatensuppe aus frischen Tomaten',
        'link': 'tomatensuppe',
        'preparationTime': '5 Minuten',
        'totalTime': '20 Minuten',
        'difficulty': 'simpel',
        'date': '31.08.2022',
        'description': 'Alle Zutaten klein hacken und im Öl andünsten. Mit Tomaten und Suppe ablöschen. Die Suppe 15 Minuten köcheln lassen und dann pürieren.  Mit Salz, Pfeffer und Basilikum abschmecken.',
        'createdBy': 'Dennis Ammen',
        'profilePicture': 'profile',
        'subtitle': 'Tomatensuppe aus frischen Tomaten',
        'ingredients': [
            {
                'ingredient': 'Tomaten',
                'amount': '250',
                'unit': 'g',
            },
            {
                'ingredient': 'Knoblauch',
                'amount': '1',
                'unit': 'Zehe(n)',
            },
            {
                'ingredient': 'Olivenöl',
                'amount': '1',
                'unit': 'EL',
            },
            {
                'ingredient': 'Gemüsebrüge',
                'amount': '150',
                'unit': 'ml',
            },
            {
                'ingredient': 'Basilikum',
                'amount': '2',
                'unit': 'Blätter',
            },           
            {
                'ingredient': 'Salz',
                'amount': '1',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Pfeffer',
                'amount': '1',
                'unit': 'Prise(n)',
            },
        ],
    },
    {
        'picture': 'spargelsuppe.jpg',
        'title': 'Spargelsuppe',
        'link': 'spargelsuppe',
        'preparationTime': '15 Minuten',
        'totalTime': '30 Minuten',
        'difficulty': 'simpel',
        'date': '31.08.2022',
        'description': 'Mit Mehl und Butter eine Mehlschwitze erzeugen. Den Spargel in kleine Stücke schneiden und in der Brühe kochen. Die Mehrschwitze mit der Suppe auffüllen und 10 Minuten kochen lassen. Mit Salz und Pfeffer abschmecken. Mit Eigelb und Suppe legieren und mit Weißwein verfeinern. Spargel in die Suppe geben und weitere 5 Minuten köcheln lassen.',
        'createdBy': 'Michel Knüpfer',
        'profilePicture': 'profile',
        'subtitle': 'Frische Spargelsuppe',
        'ingredients': [
            {
                'ingredient': 'Brühe',
                'amount': '250',
                'unit': 'ml',
            },
            {
                'ingredient': 'Spargel',
                'amount': '60',
                'unit': 'g',
            },
            {
                'ingredient': 'Butter',
                'amount': '5',
                'unit': 'g',
            },
            {
                'ingredient': 'Mehl',
                'amount': '1',
                'unit': 'TL',
            },
            {
                'ingredient': 'Eigelb',
                'amount': '0.5',
                'unit': '',
            },
            {
                'ingredient': 'Sahne',
                'amount': '30',
                'unit': 'ml',
            },
            {
                'ingredient': 'Salz',
                'amount': '0.5',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Pfeffer',
                'amount': '0.5',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Brühe',
                'amount': '1',
                'unit': 'Würfel',
            },
            {
                'ingredient': 'Weißwein',
                'amount': '1',
                'unit': 'EL',
            },
        ],
    },
     {
        'picture': 'eggburger.jpg',
        'title': 'Egg Burger',
        'link': 'eggburger',
        'preparationTime': '15 Minuten',
        'totalTime': '30 Minuten',
        'difficulty': 'simpel',
        'date': '31.08.2022',
        'description': 'Das Hackfleisch mit Salz und Pfeffer würzen und in einer Schüssel miteinander verkneten. Im Anschluss 10 Minuten ziehen lassen. Aus der Masse Patties formen. Die Patties in etwas Öl unter mehrmaligen Wenden ausbraten. Die Eier braten. Das Brötchen aufschneiden und auch kurz anbraten. Im Anschluss die Brötchen mit Ketchup bestreichen und mit Pattie, Ei, Tomaten und dem Salat belegen. Guten Appetit.',
        'createdBy': 'Dennis Ammen',
        'profilePicture': 'profile',
        'subtitle': 'Schnell und raffiniert',
        'ingredients': [
            {
                'ingredient': 'Rinderhack',
                'amount': '150',
                'unit': 'g',
            },
            {
                'ingredient': 'Ei(er)',
                'amount': '1',
                'unit': '',
            },
            {
                'ingredient': 'Zwiebel',
                'amount': '40',
                'unit': 'g',
            },
            {
                'ingredient': 'Salat',
                'amount': '2',
                'unit': 'Blätter',
            },
            {
                'ingredient': 'Tomate(n)',
                'amount': '1',
                'unit': 'kleine',
            },
            {
                'ingredient': 'Tomatenketchup',
                'amount': '1',
                'unit': 'TL',
            },
        ],
    },
    {
        'picture': 'cheeseburger.jpg',
        'title': 'Cheese Burger',
        'link': 'cheeseburger',
        'preparationTime': '15 Minuten',
        'totalTime': '30 Minuten',
        'difficulty': 'simpel',
        'date': '31.08.2022',
        'description': 'Das Hackfleisch mit Salz und Pfeffer würzen und in einer Schüssel miteinander verkneten. Im Anschluss 10 Minuten ziehen lassen. Aus der Masse Patties formen. Die Patties in etwas Öl unter mehrmaligen Wenden ausbraten. Die Patties mit Käse belegen und in den Backofen legen bis der Käse zu schmelzen beginnt. Das Brötchen aufschneiden und auch kurz anbraten. Im Anschluss mit Ketchup und Remoulade bestreichen. Das Brötchen mit dem Pattie, Tomate, Zwiebel und Gewürzgurken belegen. Guten Appetit.',
        'createdBy': 'Michel Knüpfer',
        'profilePicture': 'profile',
        'subtitle': 'I Love Burger',
        'ingredients': [
            {
                'ingredient': 'Rinderhack',
                'amount': '150',
                'unit': 'g',
            },
            {
                'ingredient': 'Cheddarkäse',
                'amount': '1',
                'unit': 'Scheibe(n)',
            },
            {
                'ingredient': 'Zwiebel',
                'amount': '40',
                'unit': 'g',
            },
            {
                'ingredient': 'Gewürtgurke(n)',
                'amount': '1',
                'unit': 'ne',
            },
            {
                'ingredient': 'Salat',
                'amount': '2',
                'unit': 'Blätter',
            },
            {
                'ingredient': 'Tomate(n)',
                'amount': '1',
                'unit': 'kleine',
            },
            {
                'ingredient': 'Tomatenketchup',
                'amount': '1',
                'unit': 'TL',
            },
            {
                'ingredient': 'Remoulade',
                'amount': '1',
                'unit': 'TL',
            },
        ],
    },
    {
        'picture': 'gebratenerreis.jpg',
        'title': 'Gebratener Reis',
        'link': 'gebratenerreis',
        'preparationTime': '20 Minuten',
        'totalTime': '30 Minuten',
        'difficulty': 'simpel',
        'date': '31.08.2022',
        'description': 'Reis unter fließenden Wasser abspülen und kochen. Zwiebeln, Knoblauch und Karotte in kleine Würfel schneiden. Wok erhitzen und Zwiebeln, Knoblauch sowie Karotte kurz anbraten. Champions und Frühlingszwiebeln klein schneiden. Sobald die Zwiebel glasig sind, das Gemüse hinzugeben. Alles kurz anbraten. Gekochten Reis hinzugeben. Eier in eine Schüssel geben und mit Salz und Pfeffer vermengen. Eier und Sojasoße in die Pfanne geben, verrühren und kurz anbraten. ',
        'createdBy': 'Michel Knüpfer',
        'profilePicture': 'profile',
        'subtitle': 'Rice to meet You',
        'ingredients': [
            {
                'ingredient': 'Reis',
                'amount': '100',
                'unit': 'g',
            },
            {
                'ingredient': 'Ei(er)',
                'amount': '1',
                'unit': '',
            },
            {
                'ingredient': 'Karotten',
                'amount': '30',
                'unit': 'g',
            },
            {
                'ingredient': 'Erbsen',
                'amount': '30',
                'unit': 'g',
            },
            {
                'ingredient': 'Frühlingszwiebel',
                'amount': '20',
                'unit': 'g',
            },
            {
                'ingredient': 'Knoblauch',
                'amount': '1',
                'unit': 'Zehe(n)',
            },
            {
                'ingredient': 'Sojasauce',
                'amount': '1',
                'unit': 'EL',
            },
            {
                'ingredient': 'Salz',
                'amount': '0.5',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Pfeffer',
                'amount': '0.5',
                'unit': 'Prise(n)',
            },
        ],
    },
    {
        'picture': 'wok.jpg',
        'title': 'Gemüsepfanne',
        'link': 'wok',
        'preparationTime': '30 Minuten',
        'totalTime': '30 Minuten',
        'difficulty': 'simpel',
        'date': '31.08.2022',
        'description': 'Zwiebeln und Knoblauch in kleine Stücke schneiden und in einer Panne anbraten. Die Champignons, Paprika, Zucchini und nach Wunsch, jedes anderes Gemüse in mundgerechte Stücke schneiden. Das Gemüse in die Pfanne geben und kurz mit anbraten. Alles mit Wasser ablöschen und einkochen lassen. Das Gericht nach Belieben mit Salz und Pfeffer würzen. ',
        'createdBy': 'Dennis Ammen',
        'profilePicture': 'profile',
        'subtitle': 'Leckere Gemüsepfanne',
        'ingredients': [
            {
                'ingredient': 'Paprika(s)',
                'amount': '0.5',
                'unit': '',
            },
            {
                'ingredient': 'Zucchini(s)',
                'amount': '0.5',
                'unit': '',
            },
            {
                'ingredient': 'Champignons',
                'amount': '1',
                'unit': 'Hand voll',
            },
            {
                'ingredient': 'Zwiebel(n)',
                'amount': '0.5',
                'unit': '',
            },
            {
                'ingredient': 'Knoblauch',
                'amount': '0.5',
                'unit': 'Zehe(n)',
            },
            {
                'ingredient': 'Salz',
                'amount': '0.5',
                'unit': 'Prise(n)',
            },
            {
                'ingredient': 'Pfeffer',
                'amount': '0.5',
                'unit': 'Prise(n)',
            },
            ],
    },

];

const recipeOfTheDay = {
    'picture': 'croissant.jpg',
    'title': 'Leckerere Croissants',
    'link': 'croissant',
    'preparationTime': '40 Min',
    'totalTime': '40 Min',
    'difficulty': 'normal',
    'date': '28.08.2006',
    'description': 'Am Vorabend fertige man aus den oben angegebenen Zutaten einen Hefeteig: Milch lauwarm werden lassen, Hefe mit etwas Zucker und Milch verrühren, kurz stehen lassen, dann mit allen Zutaten außer der Butter vermengen. Teig zugedeckt im Kühlschrank über Nacht stehen lassen. Den Teig aus dem Kühlschrank nehmen und auf einer Arbeitsfläche quadratisch ausrollen. Die Butter zwischen zwei Frischhaltefolien auf die halbe Größe des Quadrates formen, dann mit Mehl bestäuben und auf den Hefeteig legen. Das Mehl ist wichtig, da sich die Butter nicht mit dem Teig vermengen darf, da sonst kein Blätterteig entstehen kann. Also lieber etwas zu viel als zu wenig Mehl zwischen Butter und Hefeteig! Den Teig über die Butter briefumschlagartig legen, so dass von jeder Seite ein Dreieck über der Butter liegt und sie zudeckt. Dieses wird jetzt zu einem Rechteck ausgerollt, dieses Rechteck dreifach übereinander geschlagen und wieder ausgerollt. Das sollte man noch so 2 bis 3 Mal wiederholen. Dann werden Dreiecke geschnitten (etwa 12), und diese werden von der breiten Seite zu Hörnchen geformt. Den Backofen auf 220 bis 250°C vorheizen, hier scheiden sich die Geschmäcker: bis 220°C werden die Croissants (etwa 6 pro Blech) ca. 20 Minuten gebacken, bei 250°C etwa 12 Minuten. Das ist ein herrliches Frühstück!',
    'createdBy': 'Marco Loch',
    'profilePicture': 'profile',
    'subtitle': 'Bon Appétit',
    'ingredients': [
        {
            'ingredient': 'Butter',
            'amount': '250',
            'unit': 'g',
        },
        {
            'ingredient': 'Zucker',
            'amount': '50',
            'unit': 'g',
        },
        {
            'ingredient': 'Mehl',
            'amount': '500',
            'unit': 'g',
        },
        {
            'ingredient': 'Salz',
            'amount': '1',
            'unit': 'Prise(n)',
        },
        {
            'ingredient': 'Hefe',
            'amount': '42',
            'unit': 'g',
        },
        {
            'ingredient': 'Ei(er)',
            'amount': '2',
            'unit': '',
        },
        {
            'ingredient': 'Milch',
            'amount': '0.2',
            'unit': 'Liter',
        },
    ],
}
